"""Assembles a public mod's player package (<project>/dist/<Mod>/, gitignored) around a freshly built pak:

    <Mod>.pak          the pak (from build_pak.py)
    INSTALL.md         hand-written install steps, from <project>/package/INSTALL.md (Script Extender stays a link)
    Handbook.html      the player version of the docs site, generated by BuildAdvisor/docs_site/build_player_handbook.py
    Page/              Loot Advisor only: the shippable Sets page (PAGE_SOURCES)
    Media/             mod-page banner, thumbnail, logo marks and in-game screenshots, from <project>/package/Media/

The package is rebuilt from scratch every time, so nothing stale survives. build_pak.py calls release() after every
build; CI zips the same folder as <Mod>-<X.Y.Z>.zip (ci_release.py). Run it alone to re-assemble without building:
    python tools/release_files.py                         # both mods, pak taken from dist/
    python tools/release_files.py --out C:/scratch        # write <out>/<Mod>/ instead of <project>/dist/<Mod>/
    python tools/release_files.py LootAdvisor --media     # first re-make package/Media/ from MEDIA (needs Pillow and
                                                          # the local screenshots; commit the result)
Finally every file in the package must be named in INSTALL.md (a warning lists the ones that are not).
"""
import argparse
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_pak  # noqa: E402

DESKTOP = build_pak.DESKTOP                                          # the folder with the side-by-side repos
PROJECT = build_pak.PROJECT
RELEASE = build_pak.RELEASE

# The shippable Sets page: every file in the source folder is copied to <install>/Page/.
# The ship-page builder (LootAdvisor/tools/build_sets_ship.py) writes it into the mod source, which also packs it into
# the pak. Paths are relative to the folder with the repos.
PAGE_SOURCES = {"LootAdvisor": [os.path.join("LootAdvisor", "LootAdvisor", "Mods", "LootAdvisor", "Page")]}

HANDBOOK = os.path.join(DESKTOP, "BuildAdvisor", "docs_site", "build_player_handbook.py")

# package/Media/ (committed; only --media re-makes it): (source relative to the folder with the repos, file name in
# Media/, edit). Branding = option 1 "Gilded Panel". The screenshots are local files, not in any repository.
# Screenshots are re-encoded as JPEG (2560x1600, quality 85) unless an edit crops them.
# edit: None (copy as is), "jpg" (re-encode), or a dict {"crop": box, "cover": [boxes painted with the window colour]}.
_B = os.path.join("BuildAdvisor", "branding")
_S = os.path.join("LootAdvisor", "shots")
MEDIA = {
    "LootAdvisor": [
        (os.path.join(_B, "LootAdvisor", "option1_banner.png"), "LootAdvisor_banner_1920x1080.png", None),
        (os.path.join(_B, "LootAdvisor", "option1_thumb.png"), "LootAdvisor_thumbnail_1024.png", None),
        (os.path.join(_B, "LootAdvisor", "option1_mark128.png"), "LootAdvisor_mark_128.png", None),
        (os.path.join(_B, "LootAdvisor", "option1_mark64.png"), "LootAdvisor_mark_64.png", None),
        (os.path.join(_B, "LootAdvisor", "option1_wordmark.png"), "LootAdvisor_wordmark.png", None),
        (os.path.join(_S, "101_worldmap_marker_popup.png"), "Screenshot_1_world_map_marker.jpg", "jpg"),
        (os.path.join(_S, "103_minimap_marker_popup.png"), "Screenshot_2_minimap_marker.jpg", "jpg"),
        (os.path.join(_S, "95_tooltip_better_on_line.png"), "Screenshot_3_tooltip_better_on.jpg", "jpg"),
        (os.path.join(_S, "94_tooltip_astarion_fetish_next_to_game_row.png"), "Screenshot_4_tooltip_best_pick.jpg", "jpg"),
        (os.path.join(_S, "86_f6_list_dev_off.png"), "Screenshot_5_item_list_F6.jpg", "jpg"),
        (os.path.join(_S, "47_trader_marker_rainbow.png"), "Screenshot_6_frames_and_trader_marker.jpg", "jpg"),
    ],
    "BuildAdvisor": [
        (os.path.join(_B, "BuildAdvisor", "option1_banner.png"), "BuildAdvisor_banner_1920x1080.png", None),
        (os.path.join(_B, "BuildAdvisor", "option1_thumb.png"), "BuildAdvisor_thumbnail_1024.png", None),
        (os.path.join(_B, "BuildAdvisor", "option1_mark128.png"), "BuildAdvisor_mark_128.png", None),
        (os.path.join(_B, "BuildAdvisor", "option1_mark64.png"), "BuildAdvisor_mark_64.png", None),
        (os.path.join(_B, "BuildAdvisor", "option1_wordmark.png"), "BuildAdvisor_wordmark.png", None),
        # the only in-game shot of the window so far; the save's character name on line 5 is painted over
        (os.path.join(_S, "91_buildadvisor_window.png"), "Screenshot_1_advisor_window_F7.jpg",
         {"crop": (1120, 30, 2560, 790), "cover": [(1150, 197, 1269, 226)]}),
    ],
}


def project_dir(mod):
    return os.path.join(DESKTOP, PROJECT[mod])


def package_src(mod):
    """The committed part of the package: INSTALL.md and Media/."""
    return os.path.join(project_dir(mod), "package")


def package_dir(mod, out=None):
    return os.path.join(out, mod) if out else os.path.join(project_dir(mod), "dist", mod)


def copy_page(mod, dst_dir):
    written = []
    for rel in PAGE_SOURCES.get(mod, []):
        src = os.path.join(DESKTOP, rel)
        if not os.path.isdir(src):
            print("  WARNING: page source missing: %s" % src)
            continue
        page_dir = os.path.join(dst_dir, "Page")
        os.makedirs(page_dir, exist_ok=True)
        for name in sorted(os.listdir(src)):
            if os.path.isfile(os.path.join(src, name)):
                shutil.copyfile(os.path.join(src, name), os.path.join(page_dir, name))
                written.append(os.path.join(page_dir, name))
    return written


def make_handbook(mod, dst_dir):
    """Run the handbook generator; on a failed leak check no Handbook.html is written (the package check then fails)."""
    if not os.path.isfile(HANDBOOK):
        print("  WARNING: handbook generator missing: %s" % HANDBOOK)
        return []
    r = subprocess.run([sys.executable, HANDBOOK, "--mod", mod, "--out", os.path.join(dst_dir, "Handbook.html"),
                        "--media", os.path.join(package_src("LootAdvisor"), "Media")],
                       capture_output=True, text=True)
    sys.stdout.write("".join("  " + ln + "\n" for ln in r.stdout.splitlines()))
    if r.returncode:
        sys.stdout.write(r.stderr)
        print("  WARNING: Handbook.html for %s NOT updated (generator exit %d)" % (mod, r.returncode))
        return []
    return [os.path.join(dst_dir, "Handbook.html")]


def make_media(mod):
    """Re-make the committed package/Media/ from MEDIA."""
    from PIL import Image   # only needed here; the pak build itself has no dependencies
    media = os.path.join(package_src(mod), "Media")
    os.makedirs(media, exist_ok=True)
    keep = {name for _, name, _ in MEDIA.get(mod, [])}
    for name in os.listdir(media):          # drop shots that were swapped out of MEDIA
        if name not in keep:
            os.remove(os.path.join(media, name))
    written = []
    for rel, name, edit in MEDIA.get(mod, []):
        src, dst = os.path.join(DESKTOP, rel), os.path.join(media, name)
        if not os.path.isfile(src):
            print("  WARNING: media source missing: %s" % src)
            continue
        if edit is None:
            shutil.copyfile(src, dst)
        else:
            im = Image.open(src).convert("RGB")
            if isinstance(edit, dict):
                for box in edit.get("cover", []):
                    # paint over with the colour just left of the box (the window background)
                    x0, y0, x1, y1 = box
                    sample = im.crop((max(0, x0 - 6), y0, x0, y1)).resize((1, 1), Image.Resampling.BOX).getpixel((0, 0))
                    im.paste(sample, box)
                if edit.get("crop"):
                    im = im.crop(edit["crop"])
            im.save(dst, quality=85, optimize=True)
        written.append(dst)
    return written


def check_install_md(dst_dir):
    """Every file in the folder must be named in INSTALL.md."""
    md = os.path.join(dst_dir, "INSTALL.md")
    if not os.path.isfile(md):
        print("  WARNING: no INSTALL.md in %s" % dst_dir)
        return False
    text = open(md, encoding="utf-8").read()
    missing = []
    for base, _, files in os.walk(dst_dir):
        for f in files:
            if f != "INSTALL.md" and f not in text:
                missing.append(os.path.relpath(os.path.join(base, f), dst_dir))
    if missing:
        print("  WARNING: INSTALL.md does not mention: %s" % ", ".join(sorted(missing)))
    return not missing


def folder_size(d):
    return sum(os.path.getsize(os.path.join(b, f)) for b, _, fs in os.walk(d) for f in fs)


def copy_package_src(mod, dst_dir):
    src = package_src(mod)
    if not os.path.isdir(src):
        print("  WARNING: package source missing: %s" % src)
        return
    shutil.copytree(src, dst_dir, dirs_exist_ok=True)


def release(mod, pak, out=None, media=False):
    """Assemble the package of a public mod from scratch: pak, package/ (INSTALL.md, Media/), Page/, Handbook.html.
    Returns the folder, or None for a mod that has no package."""
    if mod not in RELEASE:
        return None
    if media:
        try:
            make_media(mod)
        except ImportError:
            print("  WARNING: Pillow missing, package/Media/ not re-made (pip install pillow)")
    dst_dir = package_dir(mod, out)
    if os.path.isdir(dst_dir):
        shutil.rmtree(dst_dir)
    os.makedirs(dst_dir)
    if pak:
        shutil.copyfile(pak, os.path.join(dst_dir, mod + ".pak"))
    copy_package_src(mod, dst_dir)
    copy_page(mod, dst_dir)
    make_handbook(mod, dst_dir)   # after Media/: the handbook embeds one of its screenshots
    check_install_md(dst_dir)
    print("  package %s: %.1f MB" % (dst_dir, folder_size(dst_dir) / 1e6))
    return dst_dir


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("mods", nargs="*", default=list(RELEASE))
    ap.add_argument("--out", help="write <out>/<Mod>/ instead of <project>/dist/<Mod>/")
    ap.add_argument("--media", action="store_true", help="re-make package/Media/ from MEDIA first")
    a = ap.parse_args()
    for m in a.mods:
        pak = os.path.join(build_pak.dist_dir(m), m + ".pak")
        print("%s:" % m)
        if not os.path.isfile(pak):
            print("  WARNING: %s missing (python tools/build_pak.py %s); package without a pak" % (pak, m))
        release(m, pak if os.path.isfile(pak) else None, a.out, a.media)
